In [ ]:
from tensorflow.keras.layers import Input,Dense,Lambda,Flatten,Conv2D
from tensorflow.keras.models import Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.applications.vgg19 import VGG19
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator,load_img,img_to_array
import numpy as np
import pandas as pd
from glob import glob
import matplotlib.pyplot as plt

In [ ]:
!unzip dataset.zip

Archive:  dataset.zip
   creating: dataset/
   creating: dataset/Test/
   creating: dataset/Test/without_mask/
  inflating: dataset/Test/without_mask/augmented_image_100.jpg  
  inflating: dataset/Test/without_mask/augmented_image_101.jpg  
  inflating: dataset/Test/without_mask/augmented_image_103.jpg  
  inflating: dataset/Test/without_mask/augmented_image_105.jpg  
  inflating: dataset/Test/without_mask/augmented_image_106.jpg  
  inflating: dataset/Test/without_mask/augmented_image_107.jpg  
  inflating: dataset/Test/without_mask/augmented_image_109.jpg  
  inflating: dataset/Test/without_mask/augmented_image_111.jpg  
  inflating: dataset/Test/without_mask/augmented_image_112.jpg  
  inflating: dataset/Test/without_mask/augmented_image_113.jpg  
  inflating: dataset/Test/without_mask/augmented_image_114.jpg  
  inflating: dataset/Test/without_mask/augmented_image_115.jpg  
  inflating: dataset/Test/without_mask/augmented_image_116.jpg  
  inflating: dataset/Test/without_mask/augme

In [ ]:
IMAGE_SIZE=[224,224]

train_path='/content/dataset/Train'
test_path='/content/dataset/Test'

In [ ]:
folders=glob('/content/dataset/Train/*')
len(folders)

2

In [ ]:
vgg19=VGG19(input_shape=IMAGE_SIZE+[3],weights='imagenet',include_top=False)

80142336/80134624 [==============================] - 0s 0us/step


In [ ]:
for layer in vgg19.layers:
  layer.trainable=False


In [ ]:
x=Flatten()(vgg19.output)
prediction=Dense(len(folders),activation='softmax')(x)

model=Model(inputs=vgg19.input,outputs=prediction)

In [ ]:
model.compile(optimizer='adam',loss='categorical_crossentropy')

In [ ]:
train_datagen=ImageDataGenerator(rescale=1./255,zoom_range=0.2,shear_range=0.2,horizontal_flip=True,vertical_flip=True)
test_datagen=ImageDataGenerator(rescale=1./255)

In [ ]:
train_set=train_datagen.flow_from_directory(train_path,target_size=(224,224),class_mode='categorical',batch_size=32)
test_set=train_datagen.flow_from_directory(test_path,target_size=(224,224),class_mode='categorical',batch_size=32)

Found 3360 images belonging to 2 classes.
Found 473 images belonging to 2 classes.


In [ ]:
r=model.fit(train_set,validation_data=test_set,epochs=2,steps_per_epoch=len(train_set),validation_steps=len(test_set))

Epoch 1/2
 64/105 [=================>............] - ETA: 13:42 - loss: 0.3220

/usr/local/lib/python3.6/dist-packages/PIL/Image.py:932: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  "Palette images with Transparency expressed in bytes should be "


105/105 [==============================] - 2426s 23s/step - loss: 0.2498 - val_loss: 0.2214
Epoch 2/2
105/105 [==============================] - 2431s 23s/step - loss: 0.1110 - val_loss: 0.2221


In [ ]:

from tensorflow.keras.models import load_model

model.save('model_vgg19.h5')

In [ ]:
y_pred = model.predict(test_set)

In [ ]:
y_pred = np.argmax(y_pred, axis=1)
y_pred

array([1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,

In [ ]:
model=load_model('model_vgg19.h5')

In [ ]:
img=image.load_img('/content/dataset/Test/with_mask/with_mask425.jpg',target_size=(224,224))

In [ ]:
x=image.img_to_array(img)
x

array([[[192., 170., 156.],
        [194., 172., 158.],
        [192., 170., 156.],
        ...,
        [ 94.,  85.,  86.],
        [ 95.,  81.,  78.],
        [ 83.,  73.,  72.]],

       [[197., 175., 161.],
        [195., 173., 159.],
        [192., 170., 156.],
        ...,
        [ 95.,  85.,  86.],
        [ 98.,  84.,  81.],
        [ 91.,  81.,  80.]],

       [[192., 171., 154.],
        [191., 170., 153.],
        [195., 174., 157.],
        ...,
        [ 96.,  86.,  87.],
        [ 97.,  82.,  79.],
        [ 96.,  84.,  84.]],

       ...,

       [[209., 190., 176.],
        [177., 165., 167.],
        [ 35.,  33.,  55.],
        ...,
        [162.,  77.,  46.],
        [163.,  78.,  49.],
        [163.,  79.,  43.]],

       [[209., 190., 175.],
        [144., 135., 138.],
        [ 39.,  39.,  63.],
        ...,
        [162.,  77.,  46.],
        [163.,  78.,  49.],
        [165.,  81.,  45.]],

       [[210., 191., 176.],
        [124., 118., 120.],
        [ 37.,  

In [ ]:
x.shape

(224, 224, 3)

In [ ]:
x=x/255
x=np.expand_dims(x,axis=0)
img_data=preprocess_input(x)
img_data.shape

(1, 224, 224, 3)

In [ ]:
model.predict(img_data)

array([[0.65311325, 0.34688675]], dtype=float32)

In [ ]:
a=np.argmax(model.predict(img_data), axis=1)

In [ ]:
a

array([0])